### ISSUE TITLE
unable to enable linshare-thumbnail-server.service

### ISSUE THREAD

**Issue by georgej77** [linagora/linshare-thumbnail-server#1]
I'm getting below error while enable the service of linshare-thumbnail-server.service
[root@localhost ~]# systemctl enable linshare-thumbnail-server.service
Failed to execute operation: Invalid argument

How can i solve it?

**Comment by fmartin-linagora** [comment]
Hi,
did you follow this installation [guide](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install.md#thumbnail) ?

**Comment by georgej77** [comment]
Hi Martin,

Thanks for your reply.
Yes I have followed document. Kindly help me to review it.

1)
[root@linshare system]# cat /etc/linshare/linshare.properties

#******** LinThumbnail configuration
linshare.linthumbnail.remote.mode=true
linshare.linthumbnail.dropwizard.server=
http://0.0.0.0:8090/linthumbnail?mimeType=%1$s
# key to disable thumbnail generation
linshare.documents.thumbnail.pdf.enable=true
linshare.documents.thumbnail.enable=true


2)
[root@linshare system]# ls -l /etc/linshare/linshare-thumbnail-server.yml
-rwxrwxrwx 1 root root 516 Jul 26 13:22
/etc/linshare/linshare-thumbnail-server.yml
[root@linshare system]# ls -l /usr/local/sbin/linshare-thumbnail-server.jar
-rwxrwxrwx 1 root root 27253683 Jul 26 13:23
/usr/local/sbin/linshare-thumbnail-server.jar

3)
[root@linshare system]# cat
/etc/systemd/system/linshare-thumbnail-server.service
[Unit]
Description=LinShare thumbnail server
After=network.target

[Service]
Type=idle
KillMode=process
ExecStart=/usr/bin/java -jar /usr/local/sbin/linshare-thumbnail-server.jar
server /etc/linshare/linshare-thumbnail-server.yml

[Install]
WantedBy=multi-user.target
#Alias=linshare-thumbnail-server.service

==========================================================================
4)

[root@linshare system]# systemctl status linshare-thumbnail-server.service
● linshare-thumbnail-server.service - LinShare thumbnail server
   Loaded: loaded (/etc/systemd/system/linshare-thumbnail-server.service;
enabled; vendor preset: disabled)
   *Active: active (running) *since Fri 2018-08-03 11:43:26 IST; 31s ago
 Main PID: 9036 (java)
    Tasks: 20
   CGroup: /system.slice/linshare-thumbnail-server.service
           └─9036 /usr/bin/java -jar
/usr/local/sbin/linshare-thumbnail-server.jar server
/etc/linshare/linshare-thumbnail-server.yml

Aug 03 11:43:26 linshare systemd[1]: Started LinShare thumbnail server.
Aug 03 11:43:26 linshare systemd[1]: Starting LinShare thumbnail server...

5)
[root@linshare system]# systemctl status linshare-thumbnail-server.service
● linshare-thumbnail-server.service - LinShare thumbnail server
   Loaded: loaded (/etc/systemd/system/linshare-thumbnail-server.service;
enabled; vendor preset: disabled)
  * Active: failed* (Result: exit-code) since Fri 2018-08-03 11:44:35 IST;
1min 31s ago
  Process: 9036 ExecStart=/usr/bin/java -jar
/usr/local/sbin/linshare-thumbnail-server.jar server
/etc/linshare/linshare-thumbnail-server.yml (code=exited, status=1/FAILURE)
 Main PID: 9036 (code=exited, status=1/FAILURE)

Aug 03 11:43:26 linshare systemd[1]: Started LinShare thumbnail server.
Aug 03 11:43:26 linshare systemd[1]: Starting LinShare thumbnail server...
Aug 03 11:44:35 linshare java[9036]: Multiple exceptions
Aug 03 11:44:35 linshare systemd[1]: linshare-thumbnail-server.service:
main process exited, code=exited, status=1/FAILURE
Aug 03 11:44:35 linshare systemd[1]: Unit linshare-thumbnail-server.service
entered failed state.
Aug 03 11:44:35 linshare systemd[1]: linshare-thumbnail-server.service
failed.


Another issue, I can able to login User interface. But i cannot login to
Admin interface. I have used below login credentials to access it.

Login: root@localhost.localdomain

Password: adminlinshare

I have attached here the screenshot of both interfaces.

Thanking you,
George.

**Comment by fmartin-linagora** [comment]
Hi,
If you look inside the configuration file /etc/linshare/linshare-thumbnail-server.yml, you will see the path to the logs :  currentLogFilename: /var/log/thumbnail-server.log
Take a look to this file, you may find why the service is not starting.
Fred.

**Comment by georgej77** [comment]
Hi Fred,

I'm getting below errors.

ERROR [2018-08-08 08:08:35,974] io.dropwizard.cli.ServerCommand: Unable to
start server, shutting down
! java.lang.IllegalStateException: *officeHome doesn't exist or is not a
directory*:

The system already have libreoffice.

/usr/bin/libreoffice
/usr/lib64/libreoffice
/usr/share/java/libreoffice
/usr/share/libreoffice


INFO  [2018-08-08 08:08:35,295] org.eclipse.jetty.util.log: Logging
initialized @2793ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2018-08-08 08:08:35,473] io.dropwizard.server.DefaultServerFactory:
Registering jersey handler with root path prefix: /
INFO  [2018-08-08 08:08:35,475] io.dropwizard.server.DefaultServerFactory:
Registering admin handler with root path prefix: /
INFO  [2018-08-08 08:08:35,494] io.dropwizard.server.DefaultServerFactory:
Registering jersey handler with root path prefix: /
INFO  [2018-08-08 08:08:35,494] io.dropwizard.server.DefaultServerFactory:
Registering admin handler with root path prefix: /
INFO  [2018-08-08 08:08:35,496] io.dropwizard.server.ServerFactory:
Starting LinShare-Thumbnail-Server
INFO  [2018-08-08 08:08:35,897] org.eclipse.jetty.setuid.SetUIDListener:
Opened application@68880c21{HTTP/1.1,[http/1.1]}{0.0.0.0:8090}
INFO  [2018-08-08 08:08:35,897] org.eclipse.jetty.setuid.SetUIDListener:
Opened admin@2dd2e270{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}
INFO  [2018-08-08 08:08:35,899] org.eclipse.jetty.server.Server:
jetty-9.4.z-SNAPSHOT
INFO  [2018-08-08 08:08:35,941]
org.linagora.LinThumbnail.ServiceOfficeManager: Start the service...
INFO  [2018-08-08 08:08:35,972] org.eclipse.jetty.server.AbstractConnector:
Started application@68880c21{HTTP/1.1,[http/1.1]}{0.0.0.0:8090}
WARN  [2018-08-08 08:08:35,972]
org.eclipse.jetty.util.thread.QueuedThreadPool:
dw-admin{STOPPED,1<=0<=64,i=0,q=0} rejected
org.eclipse.jetty.io.ManagedSelector$$Lambda$40/1320826684@9596ce8
ERROR [2018-08-08 08:08:35,974] io.dropwizard.cli.ServerCommand: Unable to
start server, shutting down
! java.lang.IllegalStateException: officeHome doesn't exist or is not a
directory:
! at
org.artofsolving.jodconverter.office.DefaultOfficeManagerConfiguration.buildOfficeManager(DefaultOfficeManagerConfiguration.java:160)
! at
org.linagora.LinThumbnail.ServiceOfficeManager.startOfficeManager(ServiceOfficeManager.java:77)
! at
org.linagora.LinThumbnail.impl.ThumbnailServiceImpl.start(ThumbnailServiceImpl.java:56)
! at
org.linagora.linshare.thumbnail.server.ServiceManager.start(ServiceManager.java:51)
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
! at
org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at
org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
! at org.eclipse.jetty.server.Server.start(Server.java:452)
! at
org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
! at
org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.server.Server.doStart(Server.java:419)
! ... 7 common frames omitted
! Causing: org.eclipse.jetty.util.MultiException: Multiple exceptions
! at org.eclipse.jetty.server.Server.doStart(Server.java:416)
! at
org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:74)
! at io.dropwizard.Application.run(Application.java:89)
! at
org.linagora.linshare.thumbnail.server.ThumbnailApplication.main(ThumbnailApplication.java:49)
! Suppressed: java.util.concurrent.RejectedExecutionException:
org.eclipse.jetty.io.ManagedSelector$$Lambda$40/1320826684@9596ce8
!       at
org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:384)
!       at
org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:107)
!       at
org.eclipse.jetty.io.ManagedSelector.doStart(ManagedSelector.java:96)
!       at
org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
!       at
org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
!       at
org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
!       at
org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:240)
!       at
org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
!       at
org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
!       at
org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
!       at
org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:270)
!       at
org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
!       at
org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
!       at
org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
!       at org.eclipse.jetty.server.Server.doStart(Server.java:431)
!       ... 7 common frames omitted
INFO  [2018-08-08 08:08:36,012] org.eclipse.jetty.server.AbstractConnector:
Stopped application@68880c21{HTTP/1.1,[http/1.1]}{0.0.0.0:8090}
INFO  [2018-08-08 08:09:36,013] org.eclipse.jetty.server.AbstractConnector:
Stopped admin@2dd2e270{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}
INFO  [2018-08-08 08:09:36,013]
org.linagora.LinThumbnail.ServiceOfficeManager: Stop the service...
WARN  [2018-08-08 08:09:36,013] io.dropwizard.cli.ServerCommand: Failure
during stop server
! java.lang.NullPointerException: null
! at
org.linagora.LinThumbnail.ServiceOfficeManager.stopOfficeManager(ServiceOfficeManager.java:94)
! at
org.linagora.LinThumbnail.impl.ThumbnailServiceImpl.stop(ThumbnailServiceImpl.java:61)
! at
org.linagora.linshare.thumbnail.server.ServiceManager.stop(ServiceManager.java:56)
! at io.dropwizard.lifecycle.JettyManaged.doStop(JettyManaged.java:32)
! at
org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
! at
org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
! at
org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
! at
org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
! at org.eclipse.jetty.server.Server.doStop(Server.java:523)
! at
org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:57)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:74)
! at io.dropwizard.Application.run(Application.java:89)
! at
org.linagora.linshare.thumbnail.server.ThumbnailApplication.main(ThumbnailApplication.java:49)

**Comment by fmartin-linagora** [comment]
Hi,
Which Linux Distribution are you using ?

**Comment by georgej77** [comment]
Hi Fred,

Please find the version of linux. Its Centos 7. Can you share me
recommended prerequisite for linshare implementation.

[root@linshare ~]# uname -a
Linux linshare 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018
x86_64 x86_64 x86_64 GNU/Linux
[root@linshare ~]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
[root@linshare ~]#

I have used the following linshare packages.

linshare-core-2.1.1-sql.tar.bz2
linshare-core-sql
linshare-ui-admin
linshare-ui-admin-3.1.1.tar.bz2
linshare-ui-user
linshare-ui-user-2.1.1.tar.bz2
 linshare.war

Thanks,
George.

**Comment by fmartin-linagora** [comment]
I always deployed it using Ubuntu or Debian, maybe there is an issue/side effect using RedHat.

**Comment by georgej77** [comment]
Hi Frederic,

Let me try to do a fresh installation with out installing Libreoffice.

Thanks
Jinju george

**Comment by georgej77** [comment]
Hi Frederic,

I have disabled the thumbnail option. Now i can access the admin console.
![linshare-admin](https://user-images.githubusercontent.com/41739394/44975479-2f5b7e00-af80-11e8-9656-cf2c054c54f0.jpg)
How can i get the microsoft outlook plugin for linshare.

**Comment by vemi2709** [comment]
Hi, have you solved the case, I'm having exactly the same problem. -VeM-

**Comment by georgej77** [comment]
Hi,

You mean linshare-thumbnail-server.service issue?
If yes, i have skipped that option.

**Comment by PhidarkMM** [comment]
Hello,

I just made working the thumbnail server with RH8, wanted to share with you a HOWTO

LibreOffice install:
subscription-manager repos --enable=rhel-8-for-x86_64-appstream-rpms && subscription-manager repos --enable=rhel-8-for-x86_64-baseos-rpms 
yum groupinstall "Office Suite and Productivity"
yum update
dnf update

Archive install:
cp /root/V5.1.2/thumbnail-server-2.1.1.jar /usr/local/sbin/linshare-thumbnail-server.jar

Config:
cp /root/V5.1.2/thumbnail-server-2.1.1-config.yml /etc/linshare/linshare-thumbnail-server.yml
vi /etc/linshare/linshare-thumbnail-server.yml
\# delay before deleting the temp files (the Unit is : SECOND)
duration: 100
server:
  applicationConnectors:
  \- type: http
    port: 8090
  adminConnectors:
  \- type: http
    port: 8091
logging:
  level: INFO
  loggers:
    org.linagora.linshare.thumbnail.server: INFO
  appenders:
  \- type: file
    currentLogFilename: /var/log/thumbnail-server.log
    archivedLogFilenamePattern: /var/log/thumbnail-server-%d.log.gz
    archivedFileCount: 15
    timeZone: UTC
\#   - type: syslog
\#     host: localhost
\#     facility: local0
\#   - type: console
\#     threshold: WARN
\#     target: stderr

Service configuration:
vi /etc/systemd/system/linshare-thumbnail-server.service
[Unit]
Description=LinShare thumbnail server
After=network.target

[Service]
Type=idle
KillMode=process
ExecStart=/usr/bin/java -jar /usr/local/sbin/linshare-thumbnail-server.jar server /etc/linshare/linshare-thumbnail-server.yml

[Install]
WantedBy=multi-user.target

Linshare configuration:
vi /etc/linshare/linshare.properties
\#******** LinThumbnail configuration
\# key to enable or disable thumbnail generation
linshare.documents.thumbnail.enable=true
\# key to enable remote thumbnail generation
linshare.linthumbnail.remote.mode=true
linshare.linthumbnail.dropwizard.server=http://0.0.0.0:8090/linthumbnail?mimeType=%1$s
linshare.documents.thumbnail.pdf.enable=true

Service activation:
systemctl enable linshare-thumbnail-server.service

Tomcat restart:
systemctl restart tomcat

Service start
systemctl start linshare-thumbnail-server.service

![image](https://user-images.githubusercontent.com/60786148/192765953-13209831-9647-4ca0-b62f-a451a60360f4.png)
